version: '3.8'

services:
  hz-node1:
    image: hazelcast/hazelcast:5.6.0
    ports:
      - "5701:5701"
    networks:
      - hazelcast-network
    volumes:
      - ./hazelcast.xml:/opt/hazelcast/config/hazelcast-docker.xml
    environment:
      - HZ_CLUSTERNAME=hello-world

  hz-node2:
    image: hazelcast/hazelcast:5.6.0
    ports:
      - "5702:5701"
    networks:
      - hazelcast-network
    volumes:
      - ./hazelcast.xml:/opt/hazelcast/config/hazelcast-docker.xml
    environment:
      - HZ_CLUSTERNAME=hello-world

  hz-node3:
    image: hazelcast/hazelcast:5.6.0
    ports:
      - "5703:5701"
    networks:
      - hazelcast-network
    volumes:
      - ./hazelcast.xml:/opt/hazelcast/config/hazelcast-docker.xml
    environment:
      - HZ_CLUSTERNAME=hello-world

  management-center:
    image: hazelcast/management-center:5.6.0
    ports:
      - "8080:8080"
    networks:
      - hazelcast-network
    environment:
      - HZ_MC_CLUSTER_CONFIG_1_NAME=hello-world
      - HZ_MC_CLUSTER_CONFIG_1_MEMBER_LIST=hz-node1:5701,hz-node2:5701,hz-node3:5701

networks:
  hazelcast-network:
    driver: bridge