version: '3.8'

services:
  hz-node1:
    image: hazelcast/hazelcast:5.6.0
    container_name: hz-node1
    ports:
      - "5701:5701"
    networks:
      - hazelcast-network
    volumes:
      # Maps your local file to the default config location in the container
      - ./hazelcast.xml:/opt/hazelcast/config/hazelcast-docker.xml
    environment:
      - HZ_CLUSTERNAME=hello-world
      - HZ_NETWORK_PUBLICADDRESS=192.168.88.14:5701

  hz-node2:
    image: hazelcast/hazelcast:5.6.0
    container_name: hz-node2
    ports:
      - "5702:5701"
    networks:
      - hazelcast-network
    volumes:
      - ./hazelcast.xml:/opt/hazelcast/config/hazelcast-docker.xml
    environment:
      - HZ_CLUSTERNAME=hello-world
      - HZ_NETWORK_PUBLICADDRESS=192.168.88.14:5702

  hz-node3:
    image: hazelcast/hazelcast:5.6.0
    container_name: hz-node3
    ports:
      - "5703:5701"
    networks:
      - hazelcast-network
    volumes:
      - ./hazelcast.xml:/opt/hazelcast/config/hazelcast-docker.xml
    environment:
      - HZ_CLUSTERNAME=hello-world
      - HZ_NETWORK_PUBLICADDRESS=192.168.88.14:5703

  management-center:
    image: hazelcast/management-center:5.6.0
    ports:
      - "8080:8080"
    networks:
      - hazelcast-network
    environment:
      - HZ_MC_CLUSTER_CONFIG_1_NAME=hello-world
      - HZ_MC_CLUSTER_CONFIG_1_MEMBER_LIST=hz-node1:5701,hz-node2:5702,hz-node3:5703

networks:
  hazelcast-network:
    driver: bridge